### PR TITLE
Log, Abs, Root support

### PR DESCRIPTION
**Pull request by arlm**
Supporting a few more operations:

* Logarithm, base 10 logarithm, natural (base _e_) logarithm
* Absolute value
* Radix (n<sup>th</sup> root)

### CODE REVIEW

**Comment by tompazourek** [comment]
This looks great, thanks!

The root operations looks crazy complex. I'm not sure if I'll ever be able to understand that. I'll have to check some of the linked articles.

I'm thinking maybe there could be two different root operations:

- "normal" `Root` that returns a `double`;
- `RationalRoot` that returns a `Rational`.

In most cases, I'd expect to get an irrational number out of a root operation. But this rational root algorithm could be really handy in some scenarios.

What's your opinion on that?

**Comment by arlm** [comment]
Mathematically speaking I would expect to have irrational numbers, but to be true I never used irrational numbers on computers so I have no idea how that is processed and stored. In more than 20 years of software development I have never seen or felt the need for irrational numbers.

Maybe physics, mathematics and engineers do need them, but they might have specialized libraries for that. Despite that I don't think they need irrational unlimited precision numbers or irrational big integeres.

**Comment by tompazourek** [comment]
@arlm Good point. Just to clarify: What I meant by irrational numbers in my comment was just the `double` type, I wasn't really thinking about unlimited precision irrational numbers.

**Comment by arlm** [comment]
Hahaha ... I misunderstood. For double one can use `Math.Pow(number, 0.5)` or `Math.Pow(number, 1/root)`

**Pull request merged**
